# Generated by Django 5.1.4 on 2026-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='description',
            field=models.CharField(blank=True, help_text='Additional details about the action', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('vendor_approved', 'Vendor Approved'), ('tender_published', 'Tender Published'), ('po_generated', 'Purchase Order Generated'), ('po_approved', 'Purchase Order Approved'), ('po_dispatched', 'Purchase Order Dispatched'), ('po_delivered', 'Purchase Order Delivered')], max_length=50),
        ),
    ]
