# Generated by Django 5.1.4 on 2026-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_systemlog_description_alter_systemlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('failed_login', 'Failed Login'), ('vendor_approved', 'Vendor Approved'), ('tender_created', 'Tender Created'), ('tender_published', 'Tender Published'), ('tender_closed', 'Tender Closed'), ('evaluation_submitted', 'Evaluation Submitted'), ('tender_awarded', 'Tender Awarded'), ('po_generated', 'Purchase Order Generated'), ('po_approved', 'Purchase Order Approved'), ('po_dispatched', 'Purchase Order Dispatched'), ('po_delivered', 'Purchase Order Delivered')], max_length=50),
        ),
    ]
