# Generated by Django 5.1.4 on 2026-06-13 07:38

import apps.bids.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenders', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Bid Amount (INR)')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tax / GST (%)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount (%)')),
                ('delivery_timeline_days', models.PositiveIntegerField(help_text='Number of days from PO date to delivery', verbose_name='Delivery Timeline (Days)')),
                ('warranty_period_months', models.PositiveIntegerField(default=0, verbose_name='Warranty Period (Months)')),
                ('technical_proposal', models.FileField(blank=True, help_text='Technical proposal document (PDF/Word)', null=True, upload_to=apps.bids.models.bid_technical_proposal_path)),
                ('commercial_proposal', models.FileField(blank=True, help_text='Commercial / price proposal document', null=True, upload_to=apps.bids.models.bid_commercial_proposal_path)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or comments', null=True)),
                ('is_compliant', models.BooleanField(default=True, help_text='Vendor confirms compliance with tender requirements')),
                ('emd_paid', models.BooleanField(default=False, verbose_name='EMD Paid')),
                ('emd_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='EMD Reference Number')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('approved', 'Approved / Winner'), ('withdrawn', 'Withdrawn by Vendor')], db_index=True, default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('internal_remarks', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(limit_choices_to={'status': 'open'}, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['tender', 'status'], name='bids_bid_tender__446e9d_idx'), models.Index(fields=['vendor', 'status'], name='bids_bid_vendor__3945db_idx'), models.Index(fields=['status'], name='bids_bid_status_071bbe_idx')],
                'unique_together': {('tender', 'vendor')},
            },
        ),
    ]
