# Generated by Django 5.1.4 on 2026-06-13 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('tenders', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='PO Amount (INR)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax Amount (INR)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount including Tax (INR)')),
                ('delivery_date', models.DateField(verbose_name='Expected Delivery Date')),
                ('delivery_address', models.TextField()),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
                ('terms_and_conditions', models.TextField(help_text='Standard terms and conditions for this PO')),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. 30 days net, advance 20%, etc.', max_length=255, null=True)),
                ('penalty_clause', models.TextField(blank=True, help_text='Penalty for late delivery', null=True)),
                ('line_items', models.JSONField(blank=True, default=list, help_text='List of items: [{name, qty, unit, rate, amount}]')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('in_progress', 'In Progress / Dispatched'), ('delivered', 'Delivered'), ('completed', 'Completed & Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_proof', models.FileField(blank=True, null=True, upload_to='purchase_orders/delivery/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_approved', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='evaluations.evaluation')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_generated', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='purchase_or_status_252c5c_idx'), models.Index(fields=['po_number'], name='purchase_or_po_numb_3289dd_idx'), models.Index(fields=['vendor', 'status'], name='purchase_or_vendor__7f28bd_idx')],
            },
        ),
    ]
