# Generated by Django 5.1.4 on 2026-06-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_feedback',
            field=models.TextField(blank=True, help_text='Internal feedback on vendor performance', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating out of 5 for vendor performance', null=True),
        ),
    ]
