# Generated by Django 5.1.4 on 2026-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_purchaseorder_vendor_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_agreed',
            field=models.BooleanField(default=False, verbose_name='Vendor Agreed'),
        ),
    ]
