# Generated by Django 5.1.4 on 2026-07-01 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_purchaseorder_agreed_at_purchaseorder_is_agreed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded digital signature from the vendor', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL),
        ),
    ]
