# Generated by Django 5.1.4 on 2026-06-13 07:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_score', models.DecimalField(decimal_places=2, help_text='Higher score = more competitive price', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Price Score (0-40)')),
                ('experience_score', models.DecimalField(decimal_places=2, help_text='Years of relevant experience and past performance', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Experience Score (0-30)')),
                ('warranty_score', models.DecimalField(decimal_places=2, help_text='Duration and coverage of warranty offered', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Warranty Score (0-20)')),
                ('delivery_score', models.DecimalField(decimal_places=2, help_text='Speed and reliability of proposed delivery timeline', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Delivery Score (0-10)')),
                ('total_score', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=6)),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Rank among all evaluated bids for this tender (1=best)', null=True)),
                ('price_remarks', models.TextField(blank=True, null=True)),
                ('experience_remarks', models.TextField(blank=True, null=True)),
                ('warranty_remarks', models.TextField(blank=True, null=True)),
                ('delivery_remarks', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, help_text="Evaluator's recommendation for this bid", null=True)),
                ('overall_remarks', models.TextField(blank=True, null=True)),
                ('is_winner', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Evaluation Completed'), ('pending_approval', 'Pending Manager Approval'), ('approved', 'Approved by Manager'), ('rejected', 'Rejected — Re-evaluate')], db_index=True, default='draft', max_length=20)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_approved', to=settings.AUTH_USER_MODEL)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='bids.bid')),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bid Evaluation',
                'verbose_name_plural': 'Bid Evaluations',
                'ordering': ['-total_score'],
                'indexes': [models.Index(fields=['total_score'], name='evaluations_total_s_71ee8d_idx'), models.Index(fields=['is_winner'], name='evaluations_is_winn_3edbcb_idx'), models.Index(fields=['status'], name='evaluations_status_f07c59_idx')],
            },
        ),
    ]
