# Generated by Django 5.1.4 on 2026-06-13 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('goods', 'Goods / Products'), ('services', 'Services'), ('works', 'Works / Construction'), ('consulting', 'Consulting'), ('it', 'Information Technology'), ('maintenance', 'Maintenance & Repair'), ('printing', 'Printing & Stationery'), ('transport', 'Transport & Logistics'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], db_index=True, default='goods', max_length=30)),
                ('tender_type', models.CharField(choices=[('open', 'Open Tender'), ('limited', 'Limited Tender'), ('single_source', 'Single Source'), ('rate_contract', 'Rate Contract'), ('eoi', 'Expression of Interest')], default='open', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (kg, pcs, nos, etc.)', max_length=50, null=True)),
                ('specifications', models.TextField(blank=True, help_text='Detailed technical specifications', null=True)),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Estimated Budget (INR)')),
                ('emd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Earnest Money Deposit (INR)')),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('opening_date', models.DateTimeField(help_text='Date when bid submission opens')),
                ('closing_date', models.DateTimeField(db_index=True, help_text='Last date for bid submission')),
                ('evaluation_date', models.DateTimeField(blank=True, help_text='Expected date of evaluation', null=True)),
                ('delivery_deadline', models.DateField(blank=True, help_text='Required delivery by date', null=True)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('eligibility_criteria', models.TextField(blank=True, help_text='Minimum eligibility criteria for vendors', null=True)),
                ('is_pre_bid_meeting_required', models.BooleanField(default=False)),
                ('pre_bid_meeting_date', models.DateTimeField(blank=True, null=True)),
                ('pre_bid_meeting_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tender_document', models.FileField(blank=True, help_text='Official tender notice PDF', null=True, upload_to='tenders/documents/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Manager Approval'), ('open', 'Open for Bidding'), ('closed', 'Closed'), ('under_evaluation', 'Under Evaluation'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tender',
                'verbose_name_plural': 'Tenders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'closing_date'], name='tenders_ten_status_5bccf4_idx'), models.Index(fields=['category', 'status'], name='tenders_ten_categor_796c0b_idx'), models.Index(fields=['tender_number'], name='tenders_ten_tender__4be326_idx')],
            },
        ),
    ]
