# Generated by Django 5.1.4 on 2026-06-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='custom_category',
            field=models.CharField(blank=True, help_text="Specify if category is 'Other'", max_length=100, null=True),
        ),
    ]
