# Generated by Django 5.1.4 on 2026-06-13 07:38

import apps.vendors.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('gst_number', models.CharField(max_length=15, unique=True, verbose_name='GST Number')),
                ('pan_number', models.CharField(max_length=10, unique=True, verbose_name='PAN Number')),
                ('cin_number', models.CharField(blank=True, max_length=21, null=True, unique=True, verbose_name='CIN Number')),
                ('msme_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='MSME Registration Number')),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('business_type', models.CharField(blank=True, help_text='e.g. Manufacturer, Trader, Service Provider', max_length=100, null=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_turnover', models.DecimalField(blank=True, decimal_places=2, help_text='Annual turnover in INR', max_digits=15, null=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('category_of_goods', models.TextField(blank=True, help_text='Categories / types of goods or services offered', null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True, verbose_name='IFSC Code')),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified by Procurement'), ('approved', 'Approved by Manager'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes visible only to staff', null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'procurement_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('gst_certificate', 'GST Certificate'), ('pan_card', 'PAN Card'), ('company_registration', 'Company Registration Certificate'), ('bank_details', 'Bank Details / Cancelled Cheque'), ('iso_certificate', 'ISO Certificate'), ('experience_certificate', 'Experience Certificate'), ('financial_statement', 'Financial Statement'), ('other', 'Other')], db_index=True, max_length=50)),
                ('document_name', models.CharField(blank=True, help_text='Optional friendly name for the document', max_length=255, null=True)),
                ('file', models.FileField(upload_to=apps.vendors.models.vendor_document_upload_path)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Internal remarks by verifier', null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Document',
                'verbose_name_plural': 'Vendor Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['status'], name='vendors_ven_status_2dcb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company_name'], name='vendors_ven_company_3db4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['gst_number'], name='vendors_ven_gst_num_33e6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['pan_number'], name='vendors_ven_pan_num_5788ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['vendor', 'status'], name='vendors_ven_vendor__8c286b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendordocument',
            index=models.Index(fields=['document_type', 'status'], name='vendors_ven_documen_77c62a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendordocument',
            unique_together={('vendor', 'document_type')},
        ),
    ]
