# Generated by Django 5.1.4 on 2026-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='document_retries_left',
            field=models.PositiveIntegerField(default=5, help_text='Number of document re-upload attempts allowed'),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='ai_analysis_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='ai_confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
