# Generated by Django 5.1.4 on 2026-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_document_retries_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='document_upload_counts',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks upload counts per document type'),
        ),
    ]
