# Generated by Django 5.1.4 on 2026-06-24 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_document_upload_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_system_generated', models.BooleanField(default=False)),
                ('is_read_by_vendor', models.BooleanField(default=False)),
                ('is_read_by_admin', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_vendor_messages', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Message',
                'verbose_name_plural': 'Vendor Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
