# Generated by Django 5.1.4 on 2026-06-13 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('tenders', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('vendor_registered', 'Vendor Registered'), ('vendor_verified', 'Vendor Verified'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('vendor_suspended', 'Vendor Suspended'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('tender_submitted', 'Tender Submitted for Approval'), ('tender_approved', 'Tender Approved & Published'), ('tender_rejected', 'Tender Rejected'), ('tender_published', 'New Tender Published'), ('tender_closing_soon', 'Tender Closing Soon'), ('tender_closed', 'Tender Closed'), ('tender_cancelled', 'Tender Cancelled'), ('bid_submitted', 'Bid Submitted'), ('bid_under_review', 'Bid Under Review'), ('bid_shortlisted', 'Bid Shortlisted'), ('bid_approved', 'Bid Approved — You are the Winner!'), ('bid_rejected', 'Bid Rejected'), ('evaluation_submitted', 'Evaluation Submitted for Approval'), ('evaluation_approved', 'Evaluation Approved'), ('winner_selected', 'Winner Selected'), ('po_generated', 'Purchase Order Generated'), ('po_approved', 'Purchase Order Approved'), ('po_dispatched', 'Order Dispatched'), ('po_delivered', 'Order Delivered'), ('po_completed', 'Purchase Order Completed'), ('system_alert', 'System Alert'), ('account_verified', 'Account Verified'), ('password_changed', 'Password Changed')], db_index=True, max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when notification is clicked', max_length=500, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional context data in JSON format')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bids.bid')),
                ('related_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='purchase_orders.purchaseorder')),
                ('related_tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tenders.tender')),
                ('related_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
