# Generated by Django 5.1.4 on 2026-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('vendor_registered', 'Vendor Registered'), ('vendor_verified', 'Vendor Verified'), ('vendor_approved', 'Vendor Approved'), ('vendor_rejected', 'Vendor Rejected'), ('vendor_suspended', 'Vendor Suspended'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('document_rejected', 'Document Rejected'), ('limit_reset_requested', 'Limit Reset Requested'), ('tender_submitted', 'Tender Submitted for Approval'), ('tender_approved', 'Tender Approved & Published'), ('tender_rejected', 'Tender Rejected'), ('tender_published', 'New Tender Published'), ('tender_closing_soon', 'Tender Closing Soon'), ('tender_closed', 'Tender Closed'), ('tender_cancelled', 'Tender Cancelled'), ('bid_submitted', 'Bid Submitted'), ('bid_under_review', 'Bid Under Review'), ('bid_shortlisted', 'Bid Shortlisted'), ('bid_approved', 'Bid Approved — You are the Winner!'), ('bid_rejected', 'Bid Rejected'), ('evaluation_submitted', 'Evaluation Submitted for Approval'), ('evaluation_approved', 'Evaluation Approved'), ('winner_selected', 'Winner Selected'), ('po_generated', 'Purchase Order Generated'), ('po_approved', 'Purchase Order Approved'), ('po_dispatched', 'Order Dispatched'), ('po_delivered', 'Order Delivered'), ('po_completed', 'Purchase Order Completed'), ('system_alert', 'System Alert'), ('account_verified', 'Account Verified'), ('password_changed', 'Password Changed')], db_index=True, max_length=50),
        ),
    ]
